### ISSUE TITLE
Usability of the reports ― a question

### ISSUE THREAD

**Issue by matanster** [ruedigergad/test2junit#11]
This is indeed very nice, and I wonder how might something from clojure test code get into the "Type" column in the html reports, which is the widest column out there, or any other column, apart from the currently included information of success/failure and timing of the test. E.g. some way to propagate the stdout/stderr of a test into the reports for making them more informative.

Any pointer would be appreciated :-)

**Comment by ruedigergad** [comment]
Hi,

thanks for your feedback and interest.

Regarding the "Type" column:
I just double checked. The "Type" column actually shows information for failed and erroneous tests.
See here for an example: http://ruedigergad.github.io/test2junit/test-results/html/test2junit/0_example-tests.html
By the way, I just also tweaked the output a tiny bit more and uploaded version 1.2.7.

If you are interested in tinkering with this, I think the file
https://github.com/ruedigergad/test2junit/blob/master/src/test2junit/junit.clj
is a good starting point.
junit.clj is where the XML output is generated and the Clojure test functionality is adjusted to get the data that is used for the XML output generation.

If you have more comments or questions, just let me know.



Cheers,

Ruediger

**Comment by ruedigergad** [comment]
PS:
I took some time to tinker with this on my own.
test2junit version 1.3.0 now emits stdout and stderr and, in addition, the system properties as well.
stdout is actually stdout plut stderr because I think that splitting both make it unnecessarily difficult to read stderr and stdout in context of each other.
stderr is just stderr to allow quick checks if and what was emitted to stderr.

@all please let me know your feedback regarding these changes.
As my time permits it, I will also write a brief blog post about this where I plan to discuss the changes and their implications in a bit more detail.

**Comment by ruedigergad** [comment]
PPS:
This was a good resource for looking up basic information about the junit report XML output:
http://help.catchsoftware.com/display/ET/JUnit+Format
