### ISSUE TITLE
Weird output on 1.3.3

### ISSUE THREAD

**Issue by kamituel** [ruedigergad/test2junit#16]
We've been using v1.2.2 of the library for a long time, but recently I bumped it to 1.3.3 and terminal output when running tests was now filled with many weird print statements (i.e. some random numbers were printed repeatedly).

Our custom test reporter is printing some stuff too (regular `println`'s and `prn`'s) - so something must've changed that now makes our prints and the ones from `test2junit` to conflict badly.

**Comment by ruedigergad** [comment]
Thanks a lot for your feedback.

The "weird 'random numbers' print statements" are likely caused by some shell color code escape sequences, which I added "recently" to "prettify" the console output.

I will add an option to disable this additional shell output, which should restore your working state.

Unfortunately, due to some private things, I will not be able to look into this before approximately next week. (These private circumstances are also the reason for my comparably late reply.)

If you have further remarks or comments, just let me know.

Cheers,

Ruediger

**Comment by ruedigergad** [comment]
I just uploaded test2junit 1.4.0.
This version add a ":test2junit-silent" option for the project.clj file.
If you set this to true, the output that causes your problems should be avoided.

I hope this fixes this issue for you.
If the problems persist, please let me know.



Cheers,

Ruediger
